# Generated by Django 4.2 on 2023-05-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_name_remove_user_super_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_blocked",
            field=models.DateField(default=None, null=True),
        ),
    ]
