# Generated by Django 4.2 on 2023-05-04 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_student_user_is_student_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_student",
            new_name="student",
        ),
    ]
