# Generated by Django 4.2 on 2023-05-05 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_date_blocked"),
        ("users", "0008_remove_user_followed_books"),
    ]

    operations = []
