# Generated by Django 4.2 on 2023-05-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="copies",
            name="album",
        ),
        migrations.AddField(
            model_name="copies",
            name="book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="books.book",
            ),
            preserve_default=False,
        ),
    ]
